<?php
// $Id$

/**
 *  @file This module will demonstrate some API functions amlong with devel module
 */

/**
 *  Implements hook_help()
 */
function demo_help($path, $arg)  {
    switch ($path)  {
        case 'admin/help#demo' :
            return t('This is the demo module');
    }
   
}

/**
 *  Implements hook_node_view()
 */
    function demo_node_view($node, $view_mode, $langcode) {
    
    if($node->type == 'article') {
        
  $node->content['demo_field'] = array(
      '#type' => 'markup',
      '#markup' => '<p>' . t('This is fucking demo paragraph') . '</p>',
      '#weight' => -10,
  );
  
  $node->content['demo_list'] = array(
      '#items' => array('white', 'black', 'yellow'),
      '#theme' => 'item_list',
      '#weight' => -9,
  );
      //krumo($node);

 }  else {
     if($node->type == 'page')  {
         
         $node->content['demo_listing'] = array(
             '#items' => array('Belgrade', 'Mladenaya', 'Utjeha'),
             '#theme' => 'item_list',
             '#weight' => -10,
         );
     }
 }
 

}